---
- name: "Reading the json file that contains the desired settings"
  ansible.builtin.set_fact:
    desired_settings: "{{ lookup('file', file.path) }}"

- name: "Printing the desired settings json object"
  ansible.builtin.debug:
    msg: "{{ desired_settings }}"
  tags: ["never", "debug"]

- name: "Creating SNMP entries"
  fortinet.fortios.fortios_switch_controller_snmp_user:
    vdom: "{{ vdom | default(omit, true) }}"
    state: "present"
    switch_controller_snmp_user:
      auth_proto: "{{ desired_settings['auth-proto'] | default(omit, true) }}"
      auth_pwd: "{{ snmp_password }}"
      name: "{{ desired_settings.name | default(omit, true) }}"
      priv_proto: "{{ desired_settings['priv-proto'] | default(omit, true) }}"
      priv_pwd: "{{ snmp_password }}"
      queries: "{{ desired_settings.queries | default(omit, true) }}"
      query_port: "{{ desired_settings['query-port'] | default(omit, true) }}"
      security_level: "{{ desired_settings['security-level'] | default(omit, true) }}"
  register: "output"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ output }}"
  tags: ["never", "debug"]
