---
- name: "Fetching all SNMP entries"
  ansible.builtin.include_tasks: "{{ path_common_firewall_configuration_fact }}"
  vars:
    selector: "system.snmp_user"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_directory }}"
  vars:
    path: "{{ backup_snmp_path }}"

- name: "Saving the SNMP settings in a local file"
  ansible.builtin.copy:
    content: "{{ item | to_nice_json(indent=2) }}"
    dest: "{{ backup_snmp_path }}/{{ file }}"
    mode: "0644"
  vars:
    file: "{{ ((item.name | replace(' ', '-')) + '.' + backup_extention) | lower }}"
  loop: "{{ data.meta.results | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
