---
- name: "Firewall addresses settings"
  hosts: "firewalls"

  tasks:
    - name: "Backing up the Firewall addresses settings"
      ansible.builtin.include_tasks: "{{ path_role_firewall_address }}/backup.yml"
