---
- name: "Setting up the system settings"
  hosts: "firewalls"

  tasks:
    - name: "Setting up System Settings from backup"
      ansible.builtin.include_tasks: "{{ path_role_system_settings }}/create-from-backup.yml"
