---
- name: "NTP settings"
  hosts: "firewalls"

  tasks:
    - name: "Creating NTP entries from backup"
      ansible.builtin.include_role:
        name: "ntp"
        tasks_from: "create-from-backup.yml"
