---
- name: "NTP settings"
  hosts: "firewalls"
  gather_facts: false

  tasks:
    - name: "Creating NTP entries from minimal JSON"
      ansible.builtin.include_role:
        name: "ntp"
        tasks_from: "create-from-minimal.yml"
