---
- name: "System Zone settings"
  hosts: "firewalls"

  tasks:
    - name: "Creating System Zone entries"
      ansible.builtin.include_tasks: "{{ path_role_system_zone }}/create.yml"
      tags: ["always", "debug"]
