---
- name: "Firewall Policy settings"
  hosts: "firewalls"

  tasks:
    - name: "Backing up the Firewall Policy settings"
      ansible.builtin.include_tasks: "{{ path_role_firewall_policy }}/backup.yml"
      tags: ["always", "debug"]
