---
- name: "System Interface settings"
  hosts: "firewalls"

  tasks:
    - name: "Creating System Interface from minimal JSON"
      ansible.builtin.include_role:
        name: "system_interface"
        tasks_from: "create-from-minimal.yml"
