---
- name: "System Interface settings"
  hosts: "firewalls"

  tasks:
    - name: "Backing up the System Interface settings"
      ansible.builtin.include_role:
        name: "system_interface"
        tasks_from: "backup.yml"
