---
- name: "System Zone settings"
  hosts: "firewalls"

  tasks:
    - name: "Backing up the System Zone settings"
      ansible.builtin.include_role:
        name: "system_zone"
        tasks_from: "backup.yml"
