---
- name: "System Zone settings from backup"
  hosts: "firewalls"

  tasks:
    - name: "Creating System Zone entries from backup"
      ansible.builtin.include_tasks: "{{ path_role_system_zone }}/create-from-backup.yml"
