---
- name: "DNS Server on Interface settings"
  hosts: "firewalls"
  gather_facts: false

  tasks:
    - name: "Creating DNS Server on Interface entries from minimal JSON"
      ansible.builtin.include_role:
        name: "dns_server"
        tasks_from: "create-from-minimal.yml"
