---
- name: "Firewall addresses settings from minimal config"
  hosts: "firewalls"

  tasks:
    - name: "Creating Firewall addresses entries from minimal config"
      ansible.builtin.include_tasks: "{{ path_role_firewall_address }}/create-from-minimal.yml"
