---
- name: "LDAP settings"
  hosts: "firewalls"

  tasks:
    - name: "Backing up the LDAP settings"
      ansible.builtin.include_tasks: "{{ path_role_ldap }}/backup.yml"
      tags: ["always", "debug"]
