---
- name: "Services settings"
  hosts: "firewalls"

  tasks:
    - name: "Backing up the Services settings"
      ansible.builtin.include_role:
        name: "services"
        tasks_from: "backup.yml"
