---
- name: "Static Routing settings from minimal config"
  hosts: "firewalls"

  tasks:
    - name: "Creating Static Routing entries from minimal config"
      ansible.builtin.include_tasks: "{{ path_role_static_routing }}/create-from-minimal.yml"
