---
- name: "Static Route settings"
  hosts: "firewalls"

  tasks:
    - name: "Backing up the Static Route settings"
      ansible.builtin.include_role:
        name: "static_routing"
        tasks_from: "backup.yml"
