---
- name: "Firewall Central SNAT settings"
  hosts: "firewalls"

  tasks:
    - name: "Backing up the Firewall Central SNAT settings"
      ansible.builtin.include_role:
        name: "firewall_central_snat"
        tasks_from: "backup.yml"
