---
- name: "Firewall DOS Policy settings"
  hosts: "firewalls"

  tasks:
    - name: "Backing up the Firewall DOS Policy settings"
      ansible.builtin.include_role:
        name: "firewall_dos_policy"
        tasks_from: "backup.yml"
