---
- name: "Alertemail settings"
  hosts: "firewalls"
  gather_facts: false

  tasks:
    - name: "Creating Alertemail settings from minimal JSON"
      ansible.builtin.include_role:
        name: "alertemail"
        tasks_from: "create-from-minimal.yml"
