---
- name: "Run the control machine playbook"
  ansible.builtin.import_playbook: "01-control-machine.yml"

- name: "Run the Backup playbook"
  ansible.builtin.import_playbook: "02-backup.yml"

- name: "Run the DNS playbook"
  ansible.builtin.import_playbook: "04-dns-create.yml"

- name: "Run the Firewall Addresses playbook"
  ansible.builtin.import_playbook: "05-firewall-address-create.yml"

- name: "Run the Services playbook"
  ansible.builtin.import_playbook: "06-services-create.yml"

- name: "Run the System Interface playbook"
  ansible.builtin.import_playbook: "07-system-interface-create.yml"

- name: "Run the System Zone playbook"
  ansible.builtin.import_playbook: "08-system-zone-create.yml"

- name: "Run the Firewall Policy playbook"
  ansible.builtin.import_playbook: "09-firewall-policy-create.yml"

- name: "Run the LDAP playbook"
  ansible.builtin.import_playbook: "10-ldap-create.yml"

- name: "Run the SNMP playbook"
  ansible.builtin.import_playbook: "11-snmp-create.yml"

- name: "Run the System Settings playbook"
  ansible.builtin.import_playbook: "12-system-settings-create.yml"

- name: "Run the NTP playbook"
  ansible.builtin.import_playbook: "13-ntp-create.yml"

- name: "Run the DHCP playbook"
  ansible.builtin.import_playbook: "14-dhcp-create.yml"
