---
dns_minimal_keys:
  - "authoritative"
  - "contact"
  - "dns-entry"
  - "domain"
  - "name"
  - "primary-name"
  - "status"
  - "ttl"
  - "type"
  - "view"

dns_entry_minimal_keys:
  - "canonical_name"
  - "hostname"
  - "id"
  - "ip"
  - "status"
  - "type"
