---
# - name: "Ensure Ansible Galaxy collections are installed"
#   ansible.builtin.include_tasks: "{{ path_packages_ansible_galaxy }}"
#   vars:
#     packages:
#       - {name: "fortinet.fortios"} # To work with Fortigate.

- name: "Backup a virtual domain"
  fortinet.fortios.fortios_monitor_fact:
    vdom: "{{ vdom | default(omit) }}"
    selector: "system_config_backup"
    params:
      scope: "global"
  register: "backup_output"

- name: "Save the backup information"
  ansible.builtin.copy:
    content: "{{ backup_output.meta.raw }}"
    dest: "backup.conf"
    mode: "0644"
