---
- name: "Fetching all system global settings"
  ansible.builtin.include_tasks: "{{ path_common_firewall_configuration_fact }}"
  vars:
    selector: "system_global"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
    # msg: "{{ output.meta.results }}"
    # msg: "{{ output.meta.results.hostname }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_directory }}"
  vars:
    path: "{{ backup_system_settings_path }}"

- name: "Saving the System Settings in a local file"
  ansible.builtin.copy:
    content: "{{ data.meta.results | to_nice_json(indent=2) }}"
    dest: "{{ backup_system_settings_path }}/{{ file }}"
    mode: "0644"
  vars:
    file: "{{ ((data.meta.results.hostname | replace(' ', '-')) + '.' + backup_extention) | lower }}"
