---
- name: "Restore from file"
  fortinet.fortios.fortios_monitor:
    vdom: "{{ vdom | default(omit) }}"
    selector: "restore.system.config"
    params:
      scope: "global"
      source: "upload"
      vdom: "{{ vdom | default(omit) }}"
      file_content: "{{ lookup('file', 'backup.conf') | string | b64encode }}"
