---
- name: "Fetching all DNS entries"
  fortinet.fortios.fortios_configuration_fact:
    selector: "system_dns-database"
  register: "output"

- name: "Debug"
  ansible.builtin.debug:
    # msg: "{{ output }}"
    msg: "{{ output.meta.results[0]['dns-entry'] }}"
    # msg: "{{ output.meta.results[0]['dns-entry'][0].hostname }}"

- name: "Add an dns entry in the existing obj"
  fortinet.fortios.fortios_system_dns_database:
    vdom: "{{ vdom | default(omit) }}"
    state: "present"
    member_state: "present"
    member_path: "dns_entry:id"
    system_dns_database:
      domain: "{{ domain }}"
      name: "homelab"
      dns_entry:
        - id: 44
          hostname: "teste-luciano"
          ip: "192.168.3.2"
          type: "A"
          status: "enable"
        - id: 45
          hostname: "teste-luciano"
          ip: "192.168.3.2"
          type: "PTR"
          status: "enable"
