---
- name: "Fetching the LDAP settings"
  fortinet.fortios.fortios_configuration_fact:
    vdom: "{{ vdom | default(omit) }}"
    selector: "user_ldap"
  register: "output"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ output }}"
    # msg: "{{ output.meta.results[0] }}"

# - name: "Configure LDAP server entries"
#   fortinet.fortios.fortios_user_ldap:
#     vdom: "{{ vdom | default(omit) }}"
#     state: "present"
#     user_ldap:
#       name: "edge-ldap"
#       server: "edge-ldap-01.homelab"
#       username: "cn=ldap-reader-firewall,dc=homelab"
#       cnid: "cn"
#       dn: "dc=homelab"
#       member_attr: "memberOf"
#       port: 389
#       server_identity_check : "disable"
#       type: "regular"
#       secure: "starttls"
