---
- name: "Uploading the local SSL certificate to the firewall"
  fortinet.fortios.fortios_certificate_local:
    vdom: "{{ vdom | default(omit, true) }}"
    state: "present"
    certificate_local:
      range: "global"
      source: "user"
      name: "{{ certificate_name }}"
      certificate: "{{ lookup('file', certificate_file) }}"
      private_key: "{{ lookup('file', private_key_file) }}"
      password: "{{ ssl_password }}"
  register: "output"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ output }}"
  tags: ["never", "debug"]
