---
- name: "Ensure Homebrew packages are installed"
  ansible.builtin.include_tasks: "{{ path_packages_homebrew }}"
  vars:
    update_cache: true
    upgrade: false
    packages:
      - {name: "pipx"} # A tool for installing and managing Python packages.

- name: "Installing pipx packages"
  ansible.builtin.include_tasks: "{{ path_packages_pipx_darwin }}"
  vars:
    packages:
      - {name: "ansible", install_deps: true}
      - {name: "ansible-lint"}

- name: "Ensure Ansible Galaxy collections are installed"
  ansible.builtin.include_tasks: "{{ path_packages_ansible_galaxy_darwin }}"
  vars:
    packages:
      - {name: "community.general"} # To use community.general modules.
      - {name: "fortinet.fortios"} # To work with Fortigate.
