---
- name: "Fetching all Custom Services entries"
  ansible.builtin.include_tasks: "{{ path_common_firewall_configuration_fact }}"
  vars:
    selector: "firewall.service_custom"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_directory }}"
  vars:
    path: "{{ backup_services_custom_path }}"

- name: "Saving the Custom Service backup and minimal files for entries with comment containing '{{ search_keywork }}'"
  when: item.comment is search(search_keywork, ignorecase=true)
  ansible.builtin.include_tasks: "{{ path_common_firewall_save_backup_files }}"
  vars:
    entry: "{{ (item | ansible.utils.remove_keys(target=[invalid_attribute])) }}"
    dest_dir: "{{ backup_services_custom_path }}"
    dest_basename: "{{ (item.name | replace(' ', '-')) | lower }}"
    minimal_keys: "{{ services_custom_minimal_keys }}"
  loop: "{{ data.meta.results | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
