---
- name: "Fetching all Group Services entries"
  fortinet.fortios.fortios_configuration_fact:
    vdom: "{{ vdom | default(omit) }}"
    selector: "firewall.service_group"
  register: "data"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.file:
    path: "{{ backup_services_group_path }}"
    state: "directory"
    mode: "0755"

- name: "Saving the Services with 'Ansible' keyword in the comments to a local file"
  ansible.builtin.copy:
    content: "{{ item | to_nice_json(indent=2) }}"
    dest: "{{ backup_services_group_path }}/{{ file }}"
    mode: "0644"
  vars:
    file: "{{ ((item.name | replace(' ', '-')) + '.' + backup_extention) | lower }}"
  when: item.comment is search(search_keywork, ignorecase=true)
  loop: "{{ data.meta.results | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
