---
- name: "Retrieving the backup files"
  ansible.builtin.include_tasks: "{{ path_common_firewall_get_backup_files }}"
  vars:
    paths: "{{ backup_services_custom_path }}"

- name: "Creating Custom Services entries"
  ansible.builtin.include_tasks: "add-entry-custom.yml"
  loop: "{{ backup_files.files | default([]) | sort(attribute='path') }}"
  loop_control:
    loop_var: "file"
    label: "{{ file.path }}"

- name: "Retrieving the backup files"
  ansible.builtin.include_tasks: "{{ path_common_firewall_get_backup_files }}"
  vars:
    paths: "{{ backup_services_group_path }}"

- name: "Creating Group Services entries"
  ansible.builtin.include_tasks: "add-entry-group.yml"
  loop: "{{ backup_files.files | default([]) | sort(attribute='path') }}"
  loop_control:
    loop_var: "file"
    label: "{{ file.path }}"
