---
inventory_hostname_without_domain: "{{ inventory_hostname | replace('.' + domain, '') }}"

# The id of the password saved in the secret manager. Each firewall has its own password.
ansible_password_id: "{{ inventory_hostname_without_domain ~ '-admin-password' }}"
snmp_password_id: "{{ inventory_hostname_without_domain ~ '-snmp-password' }}"

# The password of the user that will connect.
ansible_password: "{{ lookup('pipe', 'secret-tool lookup password ' + ansible_password_id) }}"

# The password that Zabbix will use to collect events and metrics from the firewall.
snmp_password: "{{ lookup('pipe', 'secret-tool lookup password ' + snmp_password_id) }}"

search_keywork: "ansible"

backup_path: "./backup"
backup_vdom_path: "{{ backup_path }}{{ (vdom is defined and vdom != '') | ternary('/' + vdom, '') }}"
backup_extention: "bkp"
backup_files_to_keep: 10

# Ansible attributes.
backup_ansible_attributes_path: "{{ backup_path }}/ansible"

# Global config.
backup_global_config_path: "{{ backup_path }}/global"

# DNS.
backup_dns_path: "{{ backup_vdom_path }}/dns"

# Firewall Address.
backup_firewall_address_path: "{{ backup_vdom_path }}/firewall_address"

# Services.
backup_services_path: "{{ backup_vdom_path }}/services"
backup_services_group_path: "{{ backup_services_path }}/groups"
backup_services_custom_path: "{{ backup_services_path }}/custom"

# System Interface.
backup_system_interface_path: "{{ backup_vdom_path }}/system_interface"

# System Zone.
backup_system_zone_path: "{{ backup_vdom_path }}/system_zone"

# Firewall Policy.
backup_firewall_policy_path: "{{ backup_vdom_path }}/firewall_policy"

# LDAP.
backup_ldap_path: "{{ backup_vdom_path }}/ldap"

# SNMP.
backup_snmp_path: "{{ backup_vdom_path }}/snmp"

# System Settings.
backup_system_settings_path: "{{ backup_vdom_path }}/system_settings"
