---
inventory_hostname_without_domain: "{{ inventory_hostname | replace('.' + domain, '') }}"

# The id of the password saved in the secret manager. Each firewall has its own password.
ansible_password_id: "{{ inventory_hostname_without_domain ~ '-admin-password' }}"
snmp_password_id: "{{ inventory_hostname_without_domain ~ '-snmp-password' }}"

# The password of the user that will connect.
# Ubuntu.
ansible_password: "{{ lookup('pipe', 'secret-tool lookup password ' + ansible_password_id) }}"
# MacOS.
# ansible_password: "{{ lookup('pipe', 'security find-generic-password -w -s ' + ansible_password_id) }}"

# The password that Zabbix will use to collect events and metrics from the firewall.
# Ubuntu.
snmp_password: "{{ lookup('pipe', 'secret-tool lookup password ' + snmp_password_id) }}"
# MacOS.
# snmp_password: "{{ lookup('pipe', 'security find-generic-password -w -s ' + snmp_password_id) }}"

search_keywork: "ansible"
invalid_attribute: "q_origin_key"

backup_path: "./backup"
backup_vdom_path: "{{ backup_path }}{{ (vdom is defined and vdom != '') | ternary('/' + vdom, '') }}"
backup_extention: "bkp"
minimal_files_extention: "*.json"
backup_files_to_keep: 10

# Ansible attributes.
backup_ansible_attributes_path: "{{ backup_path }}/ansible"

# Global config.
backup_global_config_path: "{{ backup_path }}/global"

# System VDOM.
backup_system_vdom_path: "{{ backup_path }}/system_vdom"

# DNS.
backup_dns_path: "{{ backup_vdom_path }}/dns"

# Firewall Address.
backup_firewall_address_path: "{{ backup_vdom_path }}/firewall_address"

# Services.
backup_services_path: "{{ backup_vdom_path }}/services"
backup_services_group_path: "{{ backup_services_path }}/groups"
backup_services_custom_path: "{{ backup_services_path }}/custom"

# System Interface.
backup_system_interface_path: "{{ backup_vdom_path }}/system_interface"

# System Zone.
backup_system_zone_path: "{{ backup_vdom_path }}/system_zone"

# Firewall Policy.
backup_firewall_policy_path: "{{ backup_vdom_path }}/firewall_policy"

# LDAP.
backup_ldap_path: "{{ backup_vdom_path }}/ldap"

# SNMP.
backup_snmp_path: "{{ backup_vdom_path }}/snmp"

# System Settings.
backup_system_settings_path: "{{ backup_vdom_path }}/system_settings"

# NTP.
backup_ntp_path: "{{ backup_vdom_path }}/ntp"

# DHCP.
backup_dhcp_path: "{{ backup_vdom_path }}/dhcp"

# Syslog.
backup_syslog_path: "{{ backup_vdom_path }}/syslog"

# Firewall DOS Policy.
backup_firewall_dos_policy_path: "{{ backup_vdom_path }}/firewall_dos_policy"

# Firewall Central SNAT.
backup_firewall_central_snat_path: "{{ backup_vdom_path }}/firewall_central_snat"

# System SDWAN.
backup_system_sdwan_path: "{{ backup_vdom_path }}/system_sdwan"

# Static Routing.
backup_static_routing_path: "{{ backup_vdom_path }}/static_routing"
