---
- name: "Reading the json file that contains the desired settings"
  ansible.builtin.set_fact:
    desired_settings: "{{ lookup('file', file.path) }}"

- name: "Printing the desired settings json object"
  ansible.builtin.debug:
    msg: "{{ desired_settings }}"
  tags: ["never", "debug"]

- name: "Setting DNS main settings"
  fortinet.fortios.fortios_system_dns_database:
    vdom: "{{ vdom | default(omit, true) }}"
    state: "present"
    system_dns_database:
      allow_transfer: "{{ desired_settings['allow-transfer'] | default(omit, true) }}"
      authoritative: "{{ desired_settings.authoritative | default(omit, true) }}"
      contact: "{{ desired_settings.contact | default(omit, true) }}"
      domain: "{{ desired_settings.domain | default(omit, true) }}"
      forwarder: "{{ desired_settings.forwarder | default(omit, true) }}"
      ip_primary: "{{ desired_settings['ip-primary'] | default(omit, true) }}"
      name: "{{ desired_settings.name | default(omit, true) }}"
      primary_name: "{{ desired_settings['primary-name'] | default(omit, true) }}"
      rr_max: "{{ desired_settings['rr-max'] | default(omit, true) }}"
      source_ip: "{{ desired_settings['source-ip'] | default(omit, true) }}"
      status: "{{ desired_settings.status | default(omit, true) }}"
      ttl: "{{ desired_settings.ttl | default(omit, true) }}"
      type: "{{ desired_settings.type | default(omit, true) }}"
      view: "{{ desired_settings.view | default(omit, true) }}"
  register: "output"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ output }}"
  tags: ["never", "debug"]

- name: "Creating DNS entries"
  fortinet.fortios.fortios_system_dns_database:
    vdom: "{{ vdom | default(omit, true) }}"
    state: "present"
    member_state: "present"
    member_path: "dns_entry:id"
    system_dns_database:
      name: "{{ desired_settings.name }}"
      dns_entry:
        - id: "{{ item.id }}"
          hostname: "{{ item.hostname }}"
          canonical_name: "{{ item['canonical-name'] }}"
          ip: "{{ item.ip }}"
          preference: "{{ item.preference }}"
          ttl: "{{ item.ttl }}"
          type: "{{ item.type }}"
          status: "{{ item.status }}"
  loop: "{{ desired_settings['dns-entry'] | default([]) }}"
  loop_control:
    index_var: "index"
    label: "{{ item.id }}: {{ item.hostname }} - {{ item.type }}"
  register: "output"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ output }}"
  tags: ["never", "debug"]
