---
- name: "Fetching all DNS entries"
  fortinet.fortios.fortios_configuration_fact:
    vdom: "{{ vdom | default(omit) }}"
    selector: "system_dns-database"
  register: "data"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
    # msg: "{{ data.meta.results[1] }}"
    # msg: "{{ data.meta.results[1]['dns-entry'] }}"
    # msg: "{{ data.meta.results[0]['dns-entry'][0].hostname }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.file:
    path: "{{ backup_dns_path }}"
    state: "directory"
    mode: "0755"

- name: "Saving the DNS settings in a local file"
  ansible.builtin.copy:
    content: "{{ item | to_nice_json(indent=2) }}"
    dest: "{{ backup_dns_path }}/{{ file }}"
    mode: "0644"
  vars:
    file: "{{ ((item.name | replace(' ', '-')) + '.' + backup_extention) | lower }}"
  loop: "{{ data.meta.results | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
