---
- name: "Fetching all DNS entries"
  ansible.builtin.include_tasks: "{{ path_common_firewall_configuration_fact }}"
  vars:
    selector: "system_dns-database"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
    # msg: "{{ data.meta.results[1] }}"
    # msg: "{{ data.meta.results[1]['dns-entry'] }}"
    # msg: "{{ data.meta.results[0]['dns-entry'][0].hostname }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_directory }}"
  vars:
    path: "{{ backup_dns_path }}"

- name: "Saving the DNS settings in a local file"
  ansible.builtin.copy:
    content: "{{ line | to_nice_json(indent=2) }}"
    dest: "{{ backup_dns_path }}/{{ file }}"
    mode: "0644"
  vars:
    line: >
      {{ (item
      | ansible.utils.remove_keys(target=[invalid_attribute])
      | ansible.utils.replace_keys(target=[
        {'before': 'allow-transfer' , 'after': 'allow_transfer'},
        {'before': 'dns-entry'      , 'after': 'dns_entry'},
        {'before': 'canonical-name' , 'after': 'canonical_name'},
        {'before': 'ip-primary'     , 'after': 'ip_primary'},
        {'before': 'primary-name'   , 'after': 'primary_name'},
        {'before': 'rr-max'         , 'after': 'rr_max'},
        {'before': 'source-ip'      , 'after': 'source_ip'}
      ], matching_parameter= 'regex')) }}
    file: "{{ ((item.name | replace(' ', '-')) + '.' + backup_extention) | lower }}"
  loop: "{{ data.meta.results | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
