---
system_interface_minimal_keys:
  - "alias"
  - "allowaccess"
  - "defaultgw"
  - "description"
  - "device-identification"
  - "device-user-identification"
  - "distance"
  - "dns-server-override"
  - "estimated-downstream-bandwidth"
  - "estimated-upstream-bandwidth"
  - "interface"
  - "ip"
  - "lacp-mode"
  - "lldp-reception"
  - "lldp-transmission"
  - "member"
  - "mode"
  - "monitor-bandwidth"
  - "name"
  - "role"
  - "security-mode"
  - "src-check"
  - "status"
  - "type"
  - "vlanid"
