---
- name: "Reading the json file that contains the desired settings"
  ansible.builtin.set_fact:
    desired_settings: "{{ lookup('file', file.path) }}"

- name: "Printing the desired settings json object"
  ansible.builtin.debug:
    msg: "{{ desired_settings }}"
  tags: ["never", "debug"]

- name: "Creating System Interfaces entry: {{ desired_settings.name }}"
  fortinet.fortios.fortios_system_interface:
    vdom: "{{ vdom | default(omit, true) }}"
    state: "present"
    system_interface:
      name: "{{ desired_settings.name }}"
      type: "{{ desired_settings.type }}"
      status: "{{ desired_settings.status }}"
      alias: "{{ desired_settings.alias | default(omit, true) }}"
      aggregate: "{{ desired_settings.aggregate | default(omit, true) }}"
      aggregate_type: "{{ desired_settings['aggregate-type'] | default(omit, true) }}"
      allowaccess: "{{  (desired_settings.allowaccess == '') | ternary(omit, desired_settings.allowaccess | replace(' ', ',')) }}"
      description: "{{ desired_settings.description | default(omit, true) }}"
      device_identification: "{{ desired_settings['device-identification'] | default(omit, true) }}"
      devindex: "{{ desired_settings.devindex | default(omit, true) }}"
      estimated_downstream_bandwidth: "{{ desired_settings['estimated-downstream-bandwidth'] | default(omit, true) }}"
      estimated_upstream_bandwidth: "{{ desired_settings['estimated-upstream-bandwidth'] | default(omit, true) }}"
      interface: "{{ desired_settings.interface | default(omit, true) }}"
      ip: "{{ desired_settings.ip | default(omit, true) }}"
      lacp_mode: "{{ desired_settings['lacp-mode'] | default(omit, true) }}"
      lldp_reception: "{{ desired_settings['lldp-reception'] | default(omit, true) }}"
      lldp_transmission: "{{ desired_settings['lldp-transmission'] | default(omit, true) }}"
      member: >
        {{ (desired_settings.member
        | ansible.utils.remove_keys(target=['q_origin_key'])
        | ansible.utils.replace_keys(target=[{'before': 'interface-name', 'after': 'interface_name'}]))
        | default(omit) }}
      monitor_bandwidth: "{{ desired_settings['monitor-bandwidth'] | default(omit, true) }}"
      mtu: "{{ desired_settings.mtu | default(omit, true) }}"
      role: "{{ desired_settings.role | default(omit, true) }}"
      snmp_index: "{{ desired_settings['snmp-index'] | default(omit, true) }}"
      src_check: "{{ desired_settings['src-check'] | default(omit, true) }}"
      vdom: "{{ desired_settings.vdom }}"
      vlan_protocol: "{{ desired_settings['vlan-protocol'] | default(omit, true) }}"
      vlanid: "{{ desired_settings.vlanid }}"
  register: "output"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ output }}"
  tags: ["never", "debug"]
