---
- name: "Ensure the backup directory exists"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_directory }}"

- name: "Saving the System Interface settings in a local file: {{ item.name }}"
  ansible.builtin.copy:
    content: "{{ item | to_nice_json(indent=2) }}"
    dest: "{{ path }}/{{ file }}"
    mode: "0644"
  vars:
    file: "{{ ((item.name | replace(' ', '-')) + '.' + backup_extention) | lower }}"
