---
- name: "Fetching all System Interface entries"
  ansible.builtin.include_tasks: "{{ path_common_firewall_configuration_fact }}"
  vars:
    selector: "system_interface"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
  tags: ["never", "debug"]

- name: "Backing up the System Interface settings"
  ansible.builtin.include_tasks: "backup-by-type.yml"
  vars:
    path: "{{ backup_system_interface_path }}/{{ item.type }}"
  loop: "{{ data.meta.results | default([]) | ansible.utils.remove_keys(target=[invalid_attribute]) }}"
  loop_control:
    label: "{{ item.name }} - {{ item.type }}"
