---
- name: "Ensure the backup directory exists"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_directory }}"

- name: "Saving the System Interface settings in a local file: {{ item.name }}"
  ansible.builtin.copy:
    content: "{{ line | to_nice_json(indent=2) }}"
    dest: "{{ path }}/{{ file }}"
    mode: "0644"
  vars:
    line: >
      {{ (item
      | ansible.utils.remove_keys(target=[invalid_attribute])
      | ansible.utils.replace_keys(target=[
        {'before': 'aggregate-type'         , 'after': 'aggregate_type'},
        {'before': 'device-identification'  , 'after': 'device_identification'},
        {'before': 'interface-name'         , 'after': 'interface_name'}
      ], matching_parameter= 'regex')) }}
    file: "{{ ((item.name | replace(' ', '-')) + '.' + backup_extention) | lower }}"
