---
- name: "Ensure the directory: '{{ path }}' exists"
  delegate_to: "{{ groups['ControlMachine'] | first }}"
  ansible.builtin.file:
    path: "{{ path }}"
    state: "directory"
    mode: "{{ mode | default('0755', true) }}"
