---
- name: "Saving backup file '{{ dest_basename }}.{{ backup_extention }}'"
  ansible.builtin.copy:
    content: "{{ entry | to_nice_json(indent=2) }}"
    dest: "{{ dest_dir }}/{{ dest_basename }}.{{ backup_extention }}"
    mode: "0644"

- name: "Saving minimal file '{{ dest_basename }}.{{ minimal_extention }}'"
  when: minimal_keys is defined
  ansible.builtin.copy:
    content: "{{ entry | dict2items | selectattr('key', 'in', minimal_keys) | items2dict | to_nice_json(indent=2) }}"
    dest: "{{ dest_dir }}/{{ dest_basename }}.{{ minimal_extention }}"
    mode: "0644"
