---
- name: "Reading the json file '{{ file.path }}' that contains the desired settings"
  ansible.builtin.set_fact:
    desired_settings: "{{ lookup('file', file.path) }}"

- name: "Printing the desired settings json object"
  ansible.builtin.debug:
    msg: "{{ desired_settings }}"
  tags: ["never", "debug"]

- name: "Creating a LDAP entry: {{ desired_settings.name }}"
  fortinet.fortios.fortios_user_ldap:
    vdom: "{{ vdom | default(omit, true) }}"
    state: "present"
    user_ldap:
      name: "{{ desired_settings.name }}"
      account_key_filter: "{{ desired_settings['account-key-filter'] | default(omit, true) }}"
      account_key_processing: "{{ desired_settings['account-key-processing'] | default(omit, true) }}"
      account_key_upn_san: "{{ desired_settings['account-key-upn-san'] | default(omit, true) }}"
      antiphish: "{{ desired_settings.antiphish | default(omit, true) }}"
      ca_cert: "{{ desired_settings['ca-cert'] | default(omit, true) }}"
      client_cert: "{{ desired_settings['client-cert'] | default(omit, true) }}"
      client_cert_auth: "{{ desired_settings['client-cert-auth'] | default(omit, true) }}"
      cnid: "{{ desired_settings.cnid | default(omit, true) }}"
      dn: "{{ desired_settings.dn | default(omit, true) }}"
      group_filter: "{{ desired_settings['group-filter'] | default(omit, true) }}"
      group_member_check: "{{ desired_settings['group-member-check'] | default(omit, true) }}"
      group_object_filter: "{{ desired_settings['group-object-filter'] | default(omit, true) }}"
      group_search_base: "{{ desired_settings['group-search-base'] | default(omit, true) }}"
      interface: "{{ desired_settings.interface | default(omit, true) }}"
      interface_select_method: "{{ desired_settings['interface-select-method'] | default(omit, true) }}"
      member_attr: "{{ desired_settings['member-attr'] | default(omit, true) }}"
      obtain_user_info: "{{ desired_settings['obtain-user-info'] | default(omit, true) }}"
      # password: "{{ XXX }}"
      password_attr: "{{ desired_settings['password-attr'] | default(omit, true) }}"
      password_expiry_warning: "{{ desired_settings['password-expiry-warning'] | default(omit, true) }}"
      password_renewal: "{{ desired_settings['password-renewal'] | default(omit, true) }}"
      port: "{{ desired_settings.port | default(omit, true) }}"
      search_type: "{{ desired_settings['search-type'] | default(omit, true) }}"
      secondary_server: "{{ desired_settings['secondary-server'] | default(omit, true) }}"
      secure: "{{ desired_settings.secure | default(omit, true) }}"
      server: "{{ desired_settings.server | default(omit, true) }}"
      server_identity_check: "{{ desired_settings['server-identity-check'] | default(omit, true) }}"
      source_ip: "{{ desired_settings['source-ip'] | default(omit, true) }}"
      source_port: "{{ desired_settings['source-port'] | default(omit, true) }}"
      ssl_min_proto_version: "{{ desired_settings['ssl-min-proto-version'] | default(omit, true) }}"
      tertiary_server: "{{ desired_settings['tertiary-server'] | default(omit, true) }}"
      two_factor: "{{ desired_settings['two-factor'] | default(omit, true) }}"
      two_factor_authentication: "{{ desired_settings['two-factor-authentication'] | default(omit, true) }}"
      two_factor_filter: "{{ desired_settings['two-factor-filter'] | default(omit, true) }}"
      two_factor_notification: "{{ desired_settings['two-factor-notification'] | default(omit, true) }}"
      type: "{{ desired_settings.type | default(omit, true) }}"
      user_info_exchange_server: "{{ desired_settings['user-info-exchange-server'] | default(omit, true) }}"
      username: "{{ desired_settings.username | default(omit, true) }}"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ output }}"
  tags: ["never", "debug"]
