---
- name: "Fetching all LDAP entries"
  fortinet.fortios.fortios_configuration_fact:
    vdom: "{{ vdom | default(omit, true) }}"
    selector: "user_ldap"
  register: "data"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.file:
    path: "{{ backup_ldap_path }}"
    state: "directory"
    mode: "0755"

- name: "Saving the LDAP settings in a local file"
  ansible.builtin.copy:
    content: "{{ item | to_nice_json(indent=2) }}"
    dest: "{{ backup_ldap_path }}/{{ file }}"
    mode: "0644"
  vars:
    file: "{{ ((item.name | replace(' ', '-')) + '.' + backup_extention) | lower }}"
  loop: "{{ data.meta.results | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
