---
- name: "Reading the json file that contains the desired settings"
  ansible.builtin.set_fact:
    desired_settings: "{{ lookup('file', file.path) }}"

- name: "Printing the desired settings json object"
  ansible.builtin.debug:
    msg:
      # - "{{ desired_settings }}"
      - "{{ desired_settings.type }}"
  tags: ["never", "debug"]

- name: "Setting the add entry file that will be included based on the type"
  ansible.builtin.set_fact:
    include_file: "add-entry-{{ (desired_settings.type == 'mac') | ternary('macaddr', 'subnet') }}.yml"

- name: "Creating a firewall address entry"
  ansible.builtin.include_tasks: "{{ include_file }}"
