---
- name: "Reading the json file '{{ file.path }}' that contains the desired settings"
  ansible.builtin.set_fact:
    desired_settings: "{{ lookup('file', file.path) | from_json }}"

- name: "Printing the desired settings json object"
  ansible.builtin.debug:
    msg:
      - "{{ desired_settings }}"
  tags: ["never", "debug"]

- name: "Creating firewall addresses entry: '{{ desired_settings.name }}'"
  fortinet.fortios.fortios_firewall_address:
    vdom: "{{ vdom | default(omit, true) }}"
    state: "present"
    firewall_address:
      allow_routing: "{{ desired_settings['allow-routing'] | default(omit, true) }}"
      associated_interface: "{{ desired_settings['associated-interface'] | default(omit, true) }}"
      cache_ttl: "{{ desired_settings['cache-ttl'] | default(omit, true) }}"
      clearpass_spt: "{{ desired_settings['clearpass-spt'] | default(omit, true) }}"
      color: "{{ desired_settings.color | default(omit, true) }}"
      comment: "{{ desired_settings.comment | default(omit, true) }}"
      country: "{{ desired_settings.country | default(omit, true) }}"
      fabric_object: "{{ desired_settings['fabric-object'] | default(omit, true) }}"
      filter: "{{ desired_settings.filter | default(omit, true) }}"
      fsso_group: "{{ desired_settings['fsso-group'] | default(omit, true) }}"
      hw_model: "{{ desired_settings['hw-model'] | default(omit, true) }}"
      hw_vendor: "{{ desired_settings['hw-vendor'] | default(omit, true) }}"
      interface: "{{ desired_settings.interface | default(omit, true) }}"
      list: "{{ desired_settings.list | default(omit, true) }}"
      macaddr: "{{ desired_settings.macaddr | default(omit, true) }}"
      name: "{{ desired_settings.name | default(omit, true) }}"
      node_ip_only: "{{ desired_settings['node-ip-only'] | default(omit, true) }}"
      obj_id: "{{ desired_settings['obj-id'] | default(omit, true) }}"
      obj_tag: "{{ desired_settings['obj-tag'] | default(omit, true) }}"
      obj_type: "{{ desired_settings['obj-type'] | default(omit, true) }}"
      os: "{{ desired_settings.os | default(omit, true) }}"
      route_tag: "{{ desired_settings['route-tag'] | default(omit, true) }}"
      sdn: "{{ desired_settings.sdn | default(omit, true) }}"
      sdn_addr_type: "{{ desired_settings['sdn-addr-type'] | default(omit, true) }}"
      sub_type: "{{ desired_settings['sub-type'] | default(omit, true) }}"
      subnet: "{{ desired_settings.subnet | default(omit, true) }}"
      sw_version: "{{ desired_settings['sw-version'] | default(omit, true) }}"
      tag_detection_level: "{{ desired_settings['tag-detection-level'] | default(omit, true) }}"
      tag_type: "{{ desired_settings['tag-type'] | default(omit, true) }}"
      tagging: "{{ desired_settings.tagging | default(omit, true) }}"
      type: "{{ desired_settings.type | default(omit, true) }}"
      uuid: "{{ desired_settings.uuid | default(omit, true) }}"
  register: "output"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ output }}"
  tags: ["never", "debug"]
