---
- name: "Fetching all firewall addresses"
  fortinet.fortios.fortios_configuration_fact:
    selector: "firewall_address"
  register: "data"

# - name: "Debug"
#   ansible.builtin.debug:
#     # msg: "{{ data }}"
#     msg: "{{ data.meta.results }}"
#     # msg: "{{ data.meta.results[1] }}"

- name: "Ensure the backup directory exists"
  ansible.builtin.file:
    path: "{{ backup_firewall_address_path }}"
    state: "directory"
    mode: "0755"

- name: "Saving the firewall addresses in a local file"
  ansible.builtin.copy:
    content: "{{ item | to_nice_json(indent=2) }}"
    # content: "{{ data.meta.results | to_nice_json(indent=2) }}"
    dest: "{{ backup_firewall_address_path }}/{{ file }}.{{ backup_extention }}"
    mode: "0644"
  vars:
    file: "{{ item.name }}"
    # file: "fa"
  loop: "{{ data.meta.results | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
