---
- name: "Fetching all firewall addresses"
  ansible.builtin.include_tasks: "{{ path_common_firewall_configuration_fact }}"
  vars:
    selector: "firewall_address"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
    # msg: "{{ data.meta.results }}"
    # msg: "{{ data.meta.results[1] }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_directory }}"
  vars:
    path: "{{ backup_firewall_address_path }}"

- name: "Saving firewall addresses with 'Ansible' keyword in the comments to a local file"
  ansible.builtin.copy:
    content: "{{ line | to_nice_json(indent=2) }}"
    dest: "{{ backup_firewall_address_path }}/{{ file }}"
    mode: "0644"
  vars:
    line: >
      {{ (item
      | ansible.utils.remove_keys(target=[invalid_attribute])
      | ansible.utils.replace_keys(target=[
        {'before': 'allow-routing'        , 'after': 'allow_routing'},
        {'before': 'associated-interface' , 'after': 'associated_interface'},
        {'before': 'cache-ttl'            , 'after': 'cache_ttl'},
        {'before': 'clearpass-spt'        , 'after': 'clearpass_spt'},
        {'before': 'fabric-object'        , 'after': 'fabric_object'},
        {'before': 'fsso-group'           , 'after': 'fsso_group'},
        {'before': 'node-ip-only'         , 'after': 'node_ip_only'},
        {'before': 'obj-id'               , 'after': 'obj_id'},
        {'before': 'obj-type'             , 'after': 'obj_type'},
        {'before': 'sdn-addr-type'        , 'after': 'sdn_addr_type'},
        {'before': 'sub-type'             , 'after': 'sub_type'},
        {'before': 'tag-detection-level'  , 'after': 'tag_detection_level'},
        {'before': 'tag-type'             , 'after': 'tag_type'},
      ], matching_parameter= 'regex')) }}
    file: "{{ ((item.name | replace(' ', '-')) + '.' + backup_extention) | lower }}"
  when: item.comment is search(search_keywork, ignorecase=true)
  loop: "{{ data.meta.results | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
