---
- name: "Fetching all firewall addresses"
  ansible.builtin.include_tasks: "{{ path_common_firewall_configuration_fact }}"
  vars:
    selector: "firewall_address"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
    # msg: "{{ data.meta.results }}"
    # msg: "{{ data.meta.results[1] }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_directory }}"
  vars:
    path: "{{ backup_firewall_address_path }}"

- name: "Saving firewall addresses with 'Ansible' keyword in the comments to a local file"
  ansible.builtin.copy:
    content: "{{ item | to_nice_json(indent=2) }}"
    dest: "{{ backup_firewall_address_path }}/{{ file }}"
    mode: "0644"
  vars:
    file: "{{ ((item.name | replace(' ', '-')) + '.' + backup_extention) | lower }}"
  when: item.comment is search(search_keywork, ignorecase=true)
  loop: "{{ data.meta.results | default([]) | ansible.utils.remove_keys(target=[invalid_attribute]) }}"
  loop_control:
    label: "{{ item.name }}"
