---
- name: "Fetching all firewall addresses"
  fortinet.fortios.fortios_configuration_fact:
    selector: "firewall_address"
  register: "data"

- name: "Debug"
  ansible.builtin.debug:
    # msg: "{{ data }}"
    msg: "{{ data.meta.results }}"
    # msg: "{{ data.meta.results[1] }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.file:
    path: "{{ backup_firewall_address_path }}"
    state: "directory"
    mode: "0755"

- name: "Saving firewall addresses with 'Ansible' keyword in the comments to a local file"
  ansible.builtin.copy:
    content: "{{ item | to_nice_json(indent=2) }}"
    dest: "{{ backup_firewall_address_path }}/{{ file }}"
    mode: "0644"
  vars:
    file: "{{ (item.name + '.' + backup_extention) | lower }}"
  when: item.comment is search("ansible", ignorecase=true)
  loop: "{{ data.meta.results | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
