---
- name: "Fetching up the system settings"
  fortinet.fortios.fortios_monitor_fact:
    vdom: "{{ vdom | default(omit) }}"
    selector: "system_config_backup"
    params:
      scope: "global"
  register: "data"

- name: "Ensure the backup directory exists"
  ansible.builtin.file:
    path: "{{ backup_path }}"
    state: "directory"
    mode: "0755"

- name: "Saving the settings in a local file"
  ansible.builtin.copy:
    content: "{{ data.meta.raw }}"
    dest: "{{ backup_path }}/{{ data_format }}.{{ backup_extention }}"
    mode: "0644"
  vars:
    data_format: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"

- name: "Retrieving the amount of backup files"
  ansible.builtin.find:
    paths: "{{ backup_path }}"
    patterns: "*.{{ backup_extention }}"
  register: "backup_files"

- name: "Removing old backup files"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "absent"
  loop: "{{ (backup_files.files | sort(attribute='mtime'))[0:-backup_files_to_keep] | list }}"
  loop_control:
    index_var: "index"
    label: "{{ index }} - {{ item.path }}"
