---
- name: "Backing up the Log settings"
  ansible.builtin.include_tasks: "backup-log-setting.yml"

- name: "Backing up the Log Syslogd settings"
  ansible.builtin.include_tasks: "backup-log-syslogd-setting.yml"

- name: "Backing up the Log Event Filter settings"
  ansible.builtin.include_tasks: "backup-log-eventfilter.yml"
