---
- name: "Fetching all Firewall Policy entries"
  ansible.builtin.include_tasks: "{{ path_common_firewall_configuration_fact }}"
  vars:
    selector: "firewall_policy"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_directory }}"
  vars:
    path: "{{ backup_firewall_policy_path }}"

- name: "Saving the Firewall Policy backup and minimal files"
  ansible.builtin.include_tasks: "{{ path_common_firewall_save_backup_files }}"
  vars:
    entry: >-
      {{ (item
      | ansible.utils.remove_keys(target=[invalid_attribute, 'ip-version-type', 'policy-behaviour-type', 'uuid-idx'])) }}
    dest_dir: "{{ backup_firewall_policy_path }}"
    dest_basename: "{{ (('%05d' | format(item.policyid | int)) ~ '-' ~ (item.name | replace(' ', '-'))) | lower }}"
    minimal_keys: "{{ firewall_policy_minimal_keys }}"
  loop: "{{ data.meta.results | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
