---
- name: "Fetching all Firewall Central SNAT entries"
  ansible.builtin.include_tasks: "{{ path_common_firewall_configuration_fact }}"
  vars:
    selector: "firewall_central-snat-map"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_directory }}"
  vars:
    path: "{{ backup_firewall_central_snat_path }}"

- name: "Saving the Firewall Central SNAT backup and minimal files"
  ansible.builtin.include_tasks: "{{ path_common_firewall_save_backup_files }}"
  vars:
    entry: >-
      {{ (item
      | ansible.utils.remove_keys(target=[invalid_attribute])) }}
    dest_dir: "{{ backup_firewall_central_snat_path }}"
    dest_basename: "{{ (('%03d' | format(item.policyid | int)) ~ '-' ~ (item.srcintf[0].name | replace(' ', '-'))) | lower }}"
    minimal_keys: "{{ firewall_central_snat_minimal_keys }}"
  loop: "{{ data.meta.results | default([]) }}"
  loop_control:
    label: "{{ item.srcintf[0].name }}"
