---
- name: "Fetching all System SDWAN entries"
  ansible.builtin.include_tasks: "{{ path_common_firewall_configuration_fact }}"
  vars:
    selector: "system_sdwan"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
  tags: ["never", "debug"]

- name: "Ensure the backup directory exists"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_directory }}"
  vars:
    path: "{{ backup_system_sdwan_path }}"

- name: "Saving the System SDWAN settings in a local file"
  ansible.builtin.copy:
    content: "{{ line | to_nice_json(indent=2) }}"
    dest: "{{ backup_system_sdwan_path }}/{{ file }}"
    mode: "0644"
  vars:
    line: >
      {{ (data.meta.results
      | ansible.utils.remove_keys(target=[invalid_attribute])
      | ansible.utils.replace_keys(target=[
        {'before': 'interface-name', 'after': 'interface_name'},
        {'before': 'seq-num', 'after': 'seq_num'},
        {'before': 'health-check', 'after': 'health_check'},
        {'before': 'load-balance-mode', 'after': 'load_balance_mode'},
        {'before': 'duplication-max-num', 'after': 'duplication_max_num'},
        {'before': 'spillover-threshold', 'after': 'spillover_threshold'}
      ])) }}
    file: "{{ ('SDWAN' ~ '.' ~ backup_extention) | lower }}"
