---
- name: "Retrieving the backup files"
  ansible.builtin.include_tasks: "{{ path_common_firewall_get_backup_files }}"
  vars:
    paths: "{{ backup_system_sdwan_path }}"
    patterns: "{{ backup_files_extention }}"

- name: "Creating a System SDWAN entry"
  ansible.builtin.include_tasks: "add-entry.yml"
  loop: "{{ backup_files.files | default([]) | sort(attribute='path') }}"
  loop_control:
    loop_var: "file"
    label: "{{ file.path }}"
