---
- name: "Creating the variables that will be used in the playbook"
  ansible.builtin.set_fact:
    # selector: "firewall_address"
    # selector: "firewall_central-snat-map"
    # selector: "firewall_DoS-policy"
    # selector: "firewall_policy"
    # selector: "firewall.service_custom"
    # selector: "firewall.service_group"
    # selector: "log.syslogd_setting"
    # selector: "router_static"
    # selector: "system_dns-database"
    # selector: "system_global"
    # selector: "system_interface"
    # selector: "system_ntp"
    # selector: "system_sdwan"
    # selector: "system_vdom"
    # selector: "system_zone"
    # selector: "system.dhcp_server"
    # selector: "system.snmp_user"
    selector: "user_ldap"

- name: "Fetching all entries"
  ansible.builtin.include_tasks: "{{ path_common_firewall_configuration_fact }}"

- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ data }}"
  tags: ["never", "debug"]

- name: "Creating the Ansible attributes"
  ansible.builtin.include_tasks: "{{ path_common_firewall_create_ansible_attributes }}"
  vars:
    path: "{{ backup_ansible_attributes_path }}"
    results: "{{ (data.meta.results | type_debug == 'list') | ternary(data.meta.results[0], data.meta.results) }}"
