---
- name: "Creating Ansible attributes for each selector"
  ansible.builtin.include_tasks: "create-for-selector.yml"
  loop:
    - "firewall_address"
    - "firewall_central-snat-map"
    - "firewall_DoS-policy"
    - "firewall_policy"
    - "firewall.service_custom"
    - "firewall.service_group"
    - "log.syslogd_setting"
    - "router_static"
    - "system_dns-database"
    - "system_global"
    - "system_interface"
    - "system_ntp"
    - "system_sdwan"
    - "system_vdom"
    - "system_zone"
    - "system.dhcp_server"
    - "system.snmp_user"
    - "user_ldap"
  loop_control:
    loop_var: "selector"
    label: "{{ selector }}"
